#
# Makefile for host Kernel running with stage 2 translation
#
obj-y += AbstractMachine.o
obj-y += MemRegion.o
obj-y += PageIndex.o
obj-y += PageManager.o
obj-y += PTAlloc.o
obj-y += PTWalk.o
obj-y += NPTWalk.o
