#
# Makefile for host Kernel running with stage 2 translation
#
obj-y += AbstractMachine.o
obj-y += MemRegion.o
obj-y += PageIndex.o
obj-y += PageManager.o
obj-y += PTAlloc.o
obj-y += PTWalk.o
obj-y += NPTWalk.o
obj-y += NPTOps.o
obj-y += MemManager.o
obj-y += MemoryOps.o
obj-y += VMPower.o
obj-y += BootCore.o
obj-y += BootOps.o
obj-y += BootAux.o
obj-y += Helper.o
