#
# Makefile for host Kernel running with stage 2 translation
#
obj-$(CONFIG_VERIFIED_KVM) += AbstractMachine.o
obj-$(CONFIG_VERIFIED_KVM) += MemBlock.o
obj-$(CONFIG_VERIFIED_KVM) += PageIndex.o
obj-$(CONFIG_VERIFIED_KVM) += PageMgmt.o
obj-$(CONFIG_VERIFIED_KVM) += PTAlloc.o
obj-$(CONFIG_VERIFIED_KVM) += PTWalk.o
obj-$(CONFIG_VERIFIED_KVM) += NPTWalk.o
obj-$(CONFIG_VERIFIED_KVM) += NPTOps.o
obj-$(CONFIG_VERIFIED_KVM) += MemAux.o
obj-$(CONFIG_VERIFIED_KVM) += MemOps.o
obj-$(CONFIG_VERIFIED_KVM) += VMPower.o
obj-$(CONFIG_VERIFIED_KVM) += BootCore.o
obj-$(CONFIG_VERIFIED_KVM) += BootOps.o
obj-$(CONFIG_VERIFIED_KVM) += BootAux.o
obj-$(CONFIG_VERIFIED_KVM) += Helper.o
obj-$(CONFIG_VERIFIED_KVM) += VCPUOpsAux.o
obj-$(CONFIG_VERIFIED_KVM) += VCPUOps.o
obj-$(CONFIG_VERIFIED_KVM) += el1.o
obj-$(CONFIG_VERIFIED_KVM) += el2.o
#obj-$(CONFIG_VERIFIED_KVM) += mmap.o
#obj-$(CONFIG_VERIFIED_KVM) += sysreg-sr.o
obj-$(CONFIG_VERIFIED_KVM) += sysreg-sr-opt.o
obj-$(CONFIG_VERIFIED_KVM) += hacl-20/
obj-$(CONFIG_VERIFIED_KVM) += SmmuOps.o
obj-$(CONFIG_VERIFIED_KVM) += SmmuAux.o
obj-$(CONFIG_VERIFIED_KVM) += SmmuCore.o
obj-$(CONFIG_VERIFIED_KVM) += SmmuCoreAux.o
obj-$(CONFIG_VERIFIED_KVM) += SmmuRaw.o
obj-$(CONFIG_VERIFIED_KVM) += MemHandler.o
obj-$(CONFIG_VERIFIED_KVM) += MmioPTAlloc.o
obj-$(CONFIG_VERIFIED_KVM) += MmioPTWalk.o
obj-$(CONFIG_VERIFIED_KVM) += MmioSPTWalk.o
obj-$(CONFIG_VERIFIED_KVM) += MmioSPTOps.o
obj-$(CONFIG_VERIFIED_KVM) += TrapDispatcher.o
obj-$(CONFIG_VERIFIED_KVM) += FaultHandler.o
