#
# Makefile for host Kernel running with stage 2 translation
#
obj-y += hypsec_host.o
obj-y += hypsec_mmu.o
obj-y += hypsec_helper.o
obj-y += hypsec_vcpu.o
obj-y += hypsec_boot.o
obj-y += hypsec_pvops.o
obj-y += hypsec_mmio.o
obj-y += ed25519/
obj-y += tiny-AES-c/
