#
# Makefile for host Kernel running with stage 2 translation
#
obj-y += stage2_host.o
obj-y += stage2_mmu.o
obj-y += stage2_helper.o
obj-y += stage2_vcpu.o
obj-y += stage2_boot.o
obj-y += stage2_pvops.o
#obj-y += stage2_mmio.o
obj-y += ed25519/
#obj-y += tiny-AES-c/
